"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { travelApi } from "@/lib/travel";
import s from "./studio.module.css";

type Node = {id:string;kind:"research"|"approval"|"condition"|"note"|"finish";label:string;instruction:string;tools:string[];next:string|null;otherwise:string|null;condition:"has_sources"|"ai_response"};
type Definition = {id?:string;name:string;nodes:Node[]};
type Result = {answer?:string;note?:string;decision?:string;duration_ms?:number;sources?:{title:string;url:string}[];mode?:string};
type Run = {id:string;status:string;message:string;definition:Definition;cursor:string|null;results:Record<string,Result>;error:string|null;created_at:number};
type Schedule = {id:string;message:string;due_at:number;interval_minutes:number;enabled:boolean};
type Snapshot = {definitions:Definition[];runs:Run[];schedules:Schedule[];teams:{id:string;name:string;role:string}[];members:{identity:string;role:string}[];identity:string;events:{id:number;run_id:string;kind:string;at:number;data:Record<string,unknown>}[];metrics:Record<string,number>};
const tools = ["hotels","flights","weather","activities"];
const node = (id:string,kind:Node["kind"],label:string,next:string|null):Node => ({id,kind,label,next,instruction:"",tools:[...tools],otherwise:null,condition:"has_sources"});
const initial:Definition = {name:"My travel workflow",nodes:[node("research","research","Research my trip","review"),node("review","approval","Review the research","finish"),node("finish","finish","Save the result",null)]};
const empty:Snapshot={definitions:[],runs:[],schedules:[],teams:[],members:[],identity:"",events:[],metrics:{}};
export default function Studio(){
 const [data,setData]=useState<Snapshot>(empty),[team,setTeam]=useState(""),[draft,setDraft]=useState<Definition>(initial),[selected,setSelected]=useState("research"),[definition,setDefinition]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("builder"),[runId,setRunId]=useState(""),[due,setDue]=useState(""),[interval,setIntervalValue]=useState(0),[teamName,setTeamName]=useState(""),[uid,setUid]=useState(""),[role,setRole]=useState("viewer"),[loading,setLoading]=useState(true);
 const suffix=team?`?team=${encodeURIComponent(team)}`:"";
 const load=useCallback(async()=>{try{setData(await travelApi<Snapshot>(`studio${suffix}`));}catch(e){setError(e instanceof Error?e.message:"Could not load studio.");}finally{setLoading(false);}},[suffix]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(!document.hidden)void load();},3000);return()=>clearInterval(timer);},[load]);
 async function act(path:string,body?:object,method="POST"){
  setBusy(true);setError("");setNotice("");try{const result=await travelApi<{id?:string}>(`studio/${path}${suffix}`,{method,...(body?{body:JSON.stringify(body)}:{})});await load();setNotice("Saved.");return result;}catch(e){setError(e instanceof Error?e.message:"Action failed.");return null;}finally{setBusy(false);}
 }
 const current=draft.nodes.find(n=>n.id===selected)??draft.nodes[0];
 const active=data.runs.find(r=>r.id===runId)??data.runs[0];
 const workspaceRole=team?data.teams.find(t=>t.id===team)?.role:"owner";
 const canEdit=["owner","editor"].includes(workspaceRole??""),canReview=["owner","reviewer"].includes(workspaceRole??"");
 function change(p:Partial<Node>){setDraft(d=>({...d,nodes:d.nodes.map(n=>n.id===current.id?{...n,...p}:n)}));}
 function add(kind:Node["kind"]){const id=crypto.randomUUID().slice(0,8);setDraft(d=>{const end=d.nodes.find(n=>n.kind==="finish")!;return {...d,nodes:[...d.nodes.filter(n=>n.id!==end.id).map(n=>({...n,next:n.next===end.id?id:n.next})),node(id,kind,kind==="research"?"New specialist":kind,end.id),end]};});setSelected(id);}
 function reorder(from:number,to:number){if(from===to||from<0||to<0||from>=draft.nodes.length-1||to>=draft.nodes.length-1)return;if(draft.nodes.some(n=>n.kind==="condition")){setError("Edit branch connections directly when the workflow has conditions.");return;}const list=[...draft.nodes];list.splice(to,0,list.splice(from,1)[0]);setDraft({...draft,nodes:list.map((n,i)=>({...n,next:list[i+1]?.id??null}))});}
 async function save(){const r=await act("definitions",{name:draft.name,nodes:draft.nodes});if(r?.id){setDefinition(r.id);setNotice("Workflow version saved. Existing runs keep their original version.");}}
 return <main className={s.page}>
  <header className={s.header}><Link href="/">Vacanes</Link><nav><Link href="/dashboard">Overview & memory</Link><Link href="/workflows">Travel research</Link><Link href="/planner">Chat & preferences</Link></nav></header>
  <div className={s.title}><div><p>WORKFLOW STUDIO</p><h1>Build a team.<br/>Give the journey a plan.</h1></div><label>Workspace<select value={team} onChange={e=>{setTeam(e.target.value);setDefinition("");setRunId("");setData(empty);setLoading(true);}}><option value="">Personal</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name} · {t.role}</option>)}</select></label></div>
  <div className={s.tabs} role="tablist" aria-label="Studio sections">{["builder","runs","schedules","team","activity"].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}{t==="runs"&&data.metrics.awaiting_review?` (${data.metrics.awaiting_review} to review)`:""}</button>)}</div>
  {error&&<p className={s.error} role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading&&<p>Loading workspace…</p>}
  {tab==="builder"&&<div className={s.builder}>
   <aside className={s.panel}><h2>Saved workflows</h2><p>Save a new version after editing. Running jobs retain their original graph.</p>{data.definitions.map(d=><button className={s.saved} key={d.id} onClick={()=>{setDraft(d);setSelected(d.nodes[0].id);setDefinition(d.id!);}}>{d.name}<small>{d.nodes.length} steps</small></button>)}<button onClick={()=>{setDraft(initial);setSelected("research");setDefinition("");}}>New workflow</button><Link href="/dashboard">Manage long-term memory →</Link></aside>
   <section className={s.panel}><label>Workflow name<input maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><p>Drag steps to reorder, or use the arrow buttons. Select a step to configure its agent and connections.</p><div className={s.graph}>
    {draft.nodes.map((n,i)=><div key={n.id} className={s.node} data-selected={current.id===n.id} draggable={n.kind!=="finish"} onDragStart={e=>e.dataTransfer.setData("text/plain",String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();reorder(Number(e.dataTransfer.getData("text/plain")),i);}}><button className={s.nodeSelect} onClick={()=>setSelected(n.id)}><small>{String(i+1).padStart(2,"0")} / {n.kind}</small><strong>{n.label}</strong><span>{n.next?`→ ${draft.nodes.find(x=>x.id===n.next)?.label??n.next}`:"End"}{n.otherwise?` · otherwise → ${draft.nodes.find(x=>x.id===n.otherwise)?.label}`:""}</span></button>{n.kind!=="finish"&&<div><button aria-label={`Move ${n.label} up`} disabled={i===0} onClick={()=>reorder(i,i-1)}>↑</button><button aria-label={`Move ${n.label} down`} disabled={i>=draft.nodes.length-2} onClick={()=>reorder(i,i+1)}>↓</button></div>}</div>)}
   </div><div className={s.actions}>{(["research","approval","condition","note"] as Node["kind"][]).map(k=><button disabled={draft.nodes.length>=16} key={k} onClick={()=>add(k)}>+ {k}</button>)}</div><button className={s.primary} disabled={busy||!canEdit} onClick={()=>void save()}>Save workflow version</button></section>
   <aside className={s.panel}><h2>Step configuration</h2><label>Label<input maxLength={100} value={current.label} onChange={e=>change({label:e.target.value})}/></label>{["research","note"].includes(current.kind)&&<label>{current.kind==="research"?"Agent instructions":"Note"}<textarea maxLength={2000} value={current.instruction} onChange={e=>change({instruction:e.target.value})} placeholder="Focus on quiet places and check dietary requirements."/></label>}{current.kind==="research"&&<fieldset><legend>Allowed research tools</legend>{tools.map(t=><label className={s.checkbox} key={t}><input type="checkbox" checked={current.tools.includes(t)} onChange={e=>change({tools:e.target.checked?[...current.tools,t]:current.tools.filter(x=>x!==t)})}/>{t}</label>)}<p>Unchecked tools cannot run. Saved dietary and accessibility preferences still apply.</p></fieldset>}{current.kind==="condition"&&<label>Continue when<select value={current.condition} onChange={e=>change({condition:e.target.value as Node["condition"]})}><option value="has_sources">Research has source links</option><option value="ai_response">AI response is available</option></select></label>}{current.kind!=="finish"&&<label>Next step<select value={current.next??""} onChange={e=>change({next:e.target.value})}>{draft.nodes.filter(n=>n.id!==current.id).map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label>}{current.kind==="condition"&&<label>Otherwise<select value={current.otherwise??""} onChange={e=>change({otherwise:e.target.value||null})}><option value="">Choose a branch</option>{draft.nodes.filter(n=>n.id!==current.id).map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label>}{current.kind!=="finish"&&<button onClick={()=>{const removed=current;setDraft(d=>({...d,nodes:d.nodes.filter(n=>n.id!==removed.id).map(n=>({...n,next:n.next===removed.id?removed.next:n.next,otherwise:n.otherwise===removed.id?removed.next:n.otherwise}))}));setSelected("finish");}}>Remove step</button>}<p>Approval gates pause execution. Approval continues research only; it never reserves travel or charges a card.</p></aside>
  </div>}
  {tab==="runs"&&<>
   <form className={s.panel} onSubmit={e=>{e.preventDefault();void act("runs",{definition_id:definition,message}).then(r=>{if(r?.id)setRunId(r.id);});}}><h2>Start a workflow</h2><label>Saved version<select required value={definition} onChange={e=>setDefinition(e.target.value)}><option value="">Choose a workflow</option>{data.definitions.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Travel brief<textarea required minLength={3} maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/></label>{team&&<p>This workspace will see the brief, selected travel preferences and generated results. Private chat history is excluded.</p>}<button className={s.primary} disabled={busy||!canEdit}>Start workflow</button></form>
   <div className={s.runGrid}><aside className={s.panel}>{data.runs.length===0&&<p>No runs yet. Save a workflow and start it above.</p>}{data.runs.map(r=><button className={s.saved} key={r.id} onClick={()=>setRunId(r.id)}><strong>{r.definition.name}</strong><small>{r.status.replaceAll("_"," ")} · {new Date(r.created_at*1000).toLocaleString()}</small></button>)}</aside><section className={s.panel}>{active&&<><h2>{active.definition.name}</h2><p>{active.message}</p><span className={s.status}>{active.status.replaceAll("_"," ")}</span>{active.error&&<p className={s.error}>{active.error}</p>}{active.definition.nodes.map(n=><article className={s.result} key={n.id}><h3>{active.results[n.id]?"✓ ":active.cursor===n.id?"→ ":""}{n.label}</h3>{active.results[n.id]&&<><p>{active.results[n.id].answer??active.results[n.id].note??active.results[n.id].decision??"Step completed."}</p>{active.results[n.id].mode&&<small>{active.results[n.id].mode==="ai"?"AI-assisted research":"Sample guidance"}</small>}{active.results[n.id].sources?.map((source,i)=>/^https?:\/\//.test(source.url)&&<a key={i} href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a>)}<small>{active.results[n.id].duration_ms??0} ms</small></>}</article>)}<div className={s.actions}>{active.status==="awaiting_review"&&canReview&&["approve","reject"].map(action=><button disabled={busy} key={action} onClick={()=>void act(`runs/${active.id}`,{action})}>{action}</button>)}{["failed","dead_letter"].includes(active.status)&&canEdit&&<button disabled={busy} onClick={()=>void act(`runs/${active.id}`,{action:"resume"})}>Resume from checkpoint</button>}{["queued","running","awaiting_review"].includes(active.status)&&canEdit&&<button disabled={busy} onClick={()=>void act(`runs/${active.id}`,{action:"cancel"})}>Cancel run</button>}</div><small>Run {active.id}</small></>}</section></div>
  </>}
  {tab==="schedules"&&<section className={s.panel}><h2>Scheduled workflows</h2><p>Times use your local timezone. A worker must be running. Missed recurring intervals produce one catch-up run.</p><form onSubmit={e=>{e.preventDefault();void act("schedules",{definition_id:definition,message,due_at:new Date(due).getTime()/1000,interval_minutes:interval});}}><label>Workflow<select required value={definition} onChange={e=>setDefinition(e.target.value)}><option value="">Choose a workflow</option>{data.definitions.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Brief<textarea required minLength={3} value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)}/></label><label>First run<input required type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Repeat<select value={interval} onChange={e=>setIntervalValue(Number(e.target.value))}><option value={0}>Once</option><option value={60}>Hourly</option><option value={1440}>Daily</option><option value={10080}>Weekly</option></select></label><button disabled={busy||!canEdit}>Save schedule</button></form>{data.schedules.map(x=><article className={s.result} key={x.id}><strong>{x.message}</strong><p>{new Date(x.due_at*1000).toLocaleString()} · {x.enabled?"Active":"Inactive"}</p>{x.enabled&&canEdit&&<button disabled={busy} onClick={()=>void act(`schedules/${x.id}`,undefined,"DELETE")}>Stop schedule</button>}</article>)}</section>}
  {tab==="team"&&<section className={s.panel}><h2>Shared workspaces</h2><p>Your identity: <code>{data.identity}</code></p><form onSubmit={e=>{e.preventDefault();void act("teams",{name:teamName});}}><label>New workspace name<input required maxLength={100} value={teamName} onChange={e=>setTeamName(e.target.value)}/></label><button disabled={busy||!data.identity.startsWith("user:")}>Create workspace</button>{!data.identity.startsWith("user:")&&<Link href="/login">Sign in to collaborate</Link>}</form>{team&&<><h3>Members</h3><p>Editors build and run; reviewers approve; viewers read. Only owners manage membership.</p>{data.members.map(m=><p key={m.identity}>{m.identity} — {m.role}{workspaceRole==="owner"&&m.role!=="owner"&&<button disabled={busy} onClick={()=>void act(`teams/${team}/members/${encodeURIComponent(m.identity.slice(5))}`,undefined,"DELETE")}>Remove</button>}</p>)}{workspaceRole==="owner"&&<form onSubmit={e=>{e.preventDefault();void act(`teams/${team}/members`,{uid,role});}}><label>Member Firebase UID<input required value={uid} onChange={e=>setUid(e.target.value)} /></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{["editor","reviewer","viewer"].map(r=><option key={r}>{r}</option>)}</select></label><button disabled={busy}>Add or update member</button></form>}</>}</section>}
  {tab==="activity"&&<section className={s.panel}><h2>Execution activity</h2><div className={s.metrics}>{Object.entries(data.metrics).map(([key,count])=><div key={key}><strong>{count}</strong><span>{key.replaceAll("_"," ")}</span></div>)}</div><p>Counts cover this workspace. The timeline shows the latest 200 events.</p>{data.events.map(e=><div className={s.event} key={e.id}><time>{new Date(e.at*1000).toLocaleString()}</time><strong>{e.kind.replaceAll("_"," ")}</strong><code>{e.run_id.slice(0,8)}</code></div>)}</section>}
 </main>;
}
